version: '3.9'

services:
  healthcare_app:
    container_name: healthcare_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5010:5010"
      - "5011:5011"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5011;http://+:5010
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
  healthcare.database:
    image: postgres:15.1-alpine
    container_name: healthcare.database
    ports:
      - "5432:5432"    
    environment:
      - POSTGRES_DB=healthcare_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/healthcaredb:/var/lib/postgresql/data